### ISSUE TITLE
Font UI is broken

### ISSUE THREAD

**Issue by jdrst** [isadorasophia/murder#23]
The UI for fonts is broken.
This reproduces on all systems (Win/macOS/Linux).

How to reproduce:
1. clone this repo.
2. run `dotnet run --project src\HelloMurder.Editor\HelloMurder.Editor.csproj`
3. under `Fonts` click on any font.

![image](https://github.com/isadorasophia/murder/assets/75489664/bbe3900f-22d1-4de8-a262-d0e86cec2053)
/e under linux it's a bit worse
![image](https://github.com/isadorasophia/murder/assets/75489664/45c9ca0a-815f-401f-afad-32199a79a984)

**Comment by saint11** [comment]
Wow this actually looks cool 😄
This is because ImGui actually has a triangle limit. The font file is way way too big for it to handle.
The solution is to either limit or paginate lists. Maybe 64? Ideally we can set this value in `EditorPreferences` too. We can still have problems with recursive fields, though.

I'll fix this soon, but if anyone wants to give it a go, this seem like a good first issue! 🙂

**Comment by saint11** [comment]
Fixed it here https://github.com/isadorasophia/murder/commit/ce9f23d0530b829da3b8c6246b38a1a093761be3
Lists now have a fixed limit of 128, which should be enough for most cases. I'll add pages in the future.
