### ISSUE TITLE
Agents don't move with impulse. AgentCleanupSystem runs before AgentMoverSystem

### ISSUE THREAD

**Issue by nopetrides** [isadorasophia/murder#28]
When trying to sent entity agent impulse, the impulse never updates the movement of the agent, since it gets cleared first.

Notes:
- Working out of the HelloMurder project
- I manually added the PlayerInputSystem into the Systems of the World "Hello World" to register input
![image](https://github.com/isadorasophia/murder/assets/22615608/b576fcfe-e3bf-4c9e-9147-a2cc2532c968)

Order of execution:
PlayerInputSystem FixedUpdate()
`entity.SetAgentImpulse(
    _lockMovement ? Vector2.Zero : _cachedInputAxis, direction);`
Then AgentCleanupSystem FixedUpdate runs, removing the impulse
Therefore AgentMoverSystem Update never updates the velocity.

Workaround:
Commenting out / disabling AgentCleanupSystem allows the impulse to apply correctly, but then friction is never reapplied to the agent by the cleanup system.

Perhaps it has something to do with AgentMoverSystem using Update and not FixedUpdate, or otherwise the order of operations matters here?

**Comment by saint11** [comment]
That's because any systems added to the world directly will run before any of the added features.
To intended workflow in this case is to add your PlayerInput in a Feature that runs after `AgentCleanupSystem` but earlier than the `AgentMoverSystem`.

Ideally in the future we should have a more intuitive drag and drop with the systems order.
