### ISSUE TITLE
Index outside bounds crash when editing TileGridComponent

### ISSUE THREAD

**Issue by slinaresperalta** [isadorasophia/murder#52]
### Summary:
When you try to edit the width or height of a TileGridComponent in the world view out of its bounds, it crash the editor.

### What should happen:
It should not allow to go out of bounds, without crashing.

### How to reproduce the issue:
https://github.com/isadorasophia/hellomurder/assets/94173512/8c382636-d84a-4f68-a7a1-f42fddd0fc19
https://github.com/isadorasophia/hellomurder/assets/94173512/33866940-cb0f-4085-8d88-7c2c280dc79f
https://github.com/isadorasophia/hellomurder/assets/94173512/fea96988-b3d4-4414-becd-90800d17ca99

**Comment by saint11** [comment]
Thanks for reporting that! Fixed on 8fab4f2547e029e78d7d1fd9c62d039c0582002d
Missed this because the "intended" way to edit tilesets is through here: 
![image](https://github.com/isadorasophia/murder/assets/4672703/9ad68d6a-eeea-4a54-807f-566336bed658)

**Comment by saint11** [comment]
These values shouldn't be exposed to the editor (the map grid needs to be resized internally when changing the room size)
To solve this I removed the editing capabilities on the component itself and added a shortcut to the tiles tab
![image](https://github.com/isadorasophia/murder/assets/4672703/f293083d-0bbd-4dce-892e-a3001a378238)

Fixed on 2d073c431421681d650b6a4214e74a4b074b2334

**Comment by saint11** [comment]
Fixed by 2d073c431421681d650b6a4214e74a4b074b2334
These numbers shouldn't be exposed to the editor, since we need to internally resize the grid everytime they change. To fix this disabled the editing capabilities for the TileGridComponent and added a shortcut to the correct place, the tiles editor tab.
![image](https://github.com/isadorasophia/murder/assets/4672703/7af9aead-b13d-4aee-9a0a-edbc82e2720c)
