### ISSUE TITLE
NullReferenceException on asset variable on the TilemapRenderSystem when trying to reset the value

### ISSUE THREAD

**Issue by slinaresperalta** [isadorasophia/murder#53]
### Summary:
Editor crash when trying to reset the value of a tileset inside the TilesetComponent in world.

### What should happen:
Editor shouldn't crash.

### How to reproduce the issue:
https://github.com/isadorasophia/hellomurder/assets/94173512/96657bdd-0f29-467d-a5ec-2b1b005e3bcc
https://github.com/isadorasophia/hellomurder/assets/94173512/e7509cf4-0426-4d21-ab39-884a75402c3b

**Comment by saint11** [comment]
Thanks for reporting that! Fixed on https://github.com/isadorasophia/murder/commit/8fab4f2547e029e78d7d1fd9c62d039c0582002d
Missed this because the "intended" way to edit tilesets is through here:
![293521070-9ad68d6a-eeea-4a54-807f-566336bed658](https://github.com/isadorasophia/murder/assets/4672703/0d58b286-bf3a-4329-b4ec-59bbfb3350dd)
